### ISSUE TITLE
missing code-cell outputs

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/quantecon-mini-example#14]
I can't figure out why the the code cells in quantecon-mini-example are missing (see [example](https://executablebookproject.github.io/quantecon-mini-example/docs/python_by_example.html)). They're rendered locally (see screenshot). Since the workflow is not implemented in quantecon-example, I can see the outputs render there just fine ([example](https://executablebookproject.github.io/quantecon-example/docs/numpy.html)). This is site-wide.
I wonder if it's a workflow thing. @mmcky: do you think that's possible?

![image](https://user-images.githubusercontent.com/33075058/80557913-d32e5300-8a1b-11ea-9209-503b4e7be1b9.png)

**Comment by mmcky** [comment]
Looking at one of the GitHub Actions workflows it looks like there is an issue with execution

```bash
WARNING: Execution Failed: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/learn_more.md
52
WARNING: Couldn't find cache key for notebook file mini_book/docs/learn_more.md. Outputs will not be inserted.
```

**Comment by mmcky** [comment]
But these guys seem to have been executed

```bash
Execution Succeeded: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/python_by_example.md
38
Executing: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/learn_more.md
39
Executing: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/about_py.md
40
Execution Succeeded: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/about_py.md
41
Executing: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/getting_started.md
42
Execution Succeeded: /home/runner/work/quantecon-mini-example/quantecon-mini-example/mini_book/docs/getting_started.md
```

**Comment by najuzilu** [comment]
Locally I don't get any execution errors...

**Comment by mmcky** [comment]
> Locally I don't get any execution errors...

Are you using the same `environment.yml`?

**Comment by najuzilu** [comment]
Yes!

**Comment by mmcky** [comment]
Should these be specified in `environment.yml` or leave these to be installed by the CLI tool?

```
    - git+https://github.com/ExecutableBookProject/MyST-NB.git
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
    - git+https://github.com/ExecutableBookProject/jupyter-book
    - git+https://github.com/ExecutableBookProject/sphinx-book-theme
```

**Comment by najuzilu** [comment]
I was under the impression that `git+https://github.com/ExecutableBookProject/jupyter-book` installed the updated cli tool. 

I added the rest when the outputs weren't showing thinking that I might have missed something. I don't think they're needed (except maybe `jupyter-cache[cli]`

I just recreated the env and reran the build - no errors:
<img width="1077" alt="Screen Shot 2020-04-29 at 1 32 37 PM" src="https://user-images.githubusercontent.com/33075058/80558480-e5a98c00-8a1d-11ea-9625-4f506504a95a.png">

**Comment by mmcky** [comment]
So the environment name in `enviornment.yml` didn't match the name in the workflows. That might be an issue. So I have added a PR to update that.

**Comment by najuzilu** [comment]
Oh that would explain it! I saw that showed up but then it disappeared.

**Comment by najuzilu** [comment]
I'll close this as soon as the build and deploy is successful. Thanks @mmcky !
