### ISSUE TITLE
typos in README.md

### ISSUE THREAD

**Issue by spring-haru** [ExecutableBookProject/quantecon-mini-example#18]
I realized the following when I tried to reproduce the example.

line 7:      (`a` is missing in `activate`)
2. conda `activte` quantecon-mini-example 

line 10:
jb build book/   ----->   jb build `mini_`book/
jb clean book/   ----->   jb clean `mini_`book/
jb clean --all book/  ----->  jb clean --all `mini_`book/

line 14:
`mni_` is missing like line 10

**Comment by najuzilu** [comment]
Thank you for pointing out these issues @spring-haru. I have addressed these typos in PR #20.
