### ISSUE TITLE
Top-right corner page navigation menu not active

### ISSUE THREAD

**Issue by spring-haru** [ExecutableBookProject/quantecon-mini-example#19]
In [here](https://executablebookproject.github.io/quantecon-mini-example/docs/about_py.html), the top-right corner **On this page** navigation menu does not open for `md` files with subsection heads even if a mouse cursor hovers over it.

I also cloned this repo, successfully reproduced the quantecon-mini-example, and  then added a `ipynb` file with a section head and several subsection heads. But again the On this page menu is not "activated". Are there any option to activate it?

**Comment by najuzilu** [comment]
Hi @spring-haru, the following navigation menu, which I have circled in read, cannot be "activated" as its purpose is to indicate to the user the content of the markdown page.

<img width="159" alt="Screen Shot 2020-04-29 at 7 30 32 PM" src="https://user-images.githubusercontent.com/33075058/80581168-1f938600-8a50-11ea-932e-b48263a3df30.png">

Please let me know if I misunderstood your question.

**Comment by spring-haru** [comment]
@najuzilu Yes, that is what I meant. I found out what has happened. I use macOS 10.15.4 Catalina. My default browser Safari 13.1 does NOT show the content of  **On this page**, whereas Firefox 75.0 and Chrome 81.0 do show it very nicely!! It seems to be a browser problem.

**Comment by choldgraf** [comment]
@spring-haru can you open this up in https://github.com/ExecutableBookProject/sphinx-book-theme ? We should definitely figure out that browser issue

**Comment by spring-haru** [comment]
@choldgraf I guess you meant this link https://sphinx-book-theme.readthedocs.io/en/latest/notebooks.html

Safari does not show the content. Firefox and Chrome show it, but they show it only if the mouse cursor hovers over **On this page**. This behavior is different from the quantecon-mini-example.

**Comment by choldgraf** [comment]
@spring-haru I meant could you open an issue about this in the `sphinx-book-theme` repository, because that's where the fix will need to be.

**Comment by najuzilu** [comment]
I'm closing this issue as the solution has been addressed [here](https://github.com/executablebooks/sphinx-book-theme/issues/80).
